config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get 'about', to: "pages#about"
get 'cgg', to: "pages#cgg"
get 'jazztel', to: "pages#jazztel"
get 'futuren', to: "pages#futuren"
get 'solocal', to: "pages#solocal"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def cgg
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'shared/gtm_head' %>
    <title><%= meta_title %></title>
      <meta name="description" content="<%= meta_description %>">

      <!-- Facebook Open Graph data -->
      <meta property="og:title" content="<%= meta_title %>" />
      <meta property="og:type" content="website" />
      <meta property="og:url" content="<%= request.original_url %>" />
      <meta property="og:image" content="<%= meta_image %>" />
      <meta property="og:description" content="<%= meta_description %>" />
      <meta property="og:site_name" content="<%= meta_title %>" />

      <!-- Twitter Card data -->
      <meta name="twitter:card" content="summary_large_image">
      <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:title" content="<%= meta_title %>">
      <meta name="twitter:description" content="<%= meta_description %>">
      <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
      <meta name="twitter:image:src" content="<%= meta_image %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="turbolinks-visit-control" content="reload">

    <!-- Global site tag (gtag.js) - Google Analytics -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-7XJ9BGL3LC"></script>
      <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'G-7XJ9BGL3LC');
      </script>

  </head>

  <body>
    <%= render 'shared/gtm_body' %>
     <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/cgg.html.erb
<section class="pt-4 pt-md-11">
      <div class="container">
        <div class="row align-items-center">
          <div class="col-12 col-md-5 order-md-2">

            <!-- Image -->
            <%= image_tag("photos/logo_CGG.png", class: "img-fluid mb-6 mb-md-0") %>

          </div>
          <div class="col-12 col-md-7 order-md-1">

            <!-- Heading -->
            <h1 class="display-4">
              A full cross-asset cycle <br>
              <span class="text-primary">into a distressed sector.</span>
            </h1>

            <!-- Text -->
            <p class="lead text-muted mb-0">
              Help a data driven company to refocus on its core knowledge and endure its toughest capex cycle
            </p>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </section>

    <!-- ARTICLES -->
    <section class="pt-8 pt-md-11">
      <div class="container">
        <div class="row">
          <div class="col-12">

            <!-- Heading -->
            <h2 class="mb-0">
              Oil price war.
            </h2>

            <!--  -->
            <p class="mb-5 text-muted">
              Time ahead of the peak.
            </p>

          </div>
        </div> <!-- / .row -->
        <div class="row">
          <div class="col-12">

            <!-- Card -->
            <div class="card card-row shadow-light-lg mb-6">
              <div class="row gx-0">
                <div class="col-12">

                  <!-- Badge -->
                  <span class="badge rounded-pill bg-gray-600 badge-float badge-float-outside">
                    <span class="h6 text-uppercase">Featured</span>
                  </span>

                </div>
                  <a class="col-12 col-md-6 order-md-2 bg-cover card-img-end">

                  <!-- Image (placeholder) -->
                  <canvas id="myChartpriceCl"></canvas>


                  <!-- Shape -->
                  <div class="shape shape-start shape-fluid-y svg-shim text-white d-none d-md-block">
                  </div>

                </a>
                <div class="col-12 col-md-6 order-md-1">

                  <!-- Body -->
                  <div class="card-body">

                    <!-- Heading -->
                    <h3>
                      Oil barrel went fron 124$ to 34$ in 18 mths.
                    </h3>

                    <!-- Text -->
                    <p class="mb-0 text-muted">
                      For the World bank, the drop was one of the three biggest declines since World War II and the longest lasting
                      since the supply-driven collapse of 1986.
                    </p>

                  </div>

                  <!-- Meta -->
                  <a class="card-meta" href="#!">

                    <!-- Divider -->
                    <hr class="card-meta-divider">

                    <!-- Avatar -->
                    <div class="avatar avatar-sm me-2">
                      <%= image_tag("avatars/avatar-fix.jpg", class: "avatar-img rounded-circle") %>
                    </div>

                    <!-- Author -->
                    <h6 class="text-uppercase text-muted me-2 mb-0">
                      François-Xavier Baud
                    </h6>

                    <!-- Date -->
                    <p class="h6 text-uppercase text-muted mb-0 ms-auto">
                      <time datetime="2019-05-31">May 17</time>
                    </p>

                  </a>

                </div>

              </div> <!-- / .row -->
            </div>

            <!-- Card -->
            <div class="card card-row shadow-light-lg mb-6">
              <div class="row gx-0">
                <div class="col-12">

                  <!-- Badge -->
                  <span class="badge rounded-pill bg-gray-600 badge-float badge-float-outside">
                    <span class="h6 text-uppercase">Featured</span>
                  </span>

                </div>
                <a class="col-12 col-md-6 bg-cover card-img-start">

                  <!-- Image (placeholder) -->
                  <canvas id="myChartpriceCgg"></canvas>


                  <!-- Shape -->
                  <div class="shape shape-end shape-fluid-y svg-shim text-white d-none d-md-block">
                  </div>

                </a>
                <div class="col-12 col-md-6">

                  <!-- Body -->
                  <a class="card-body" href="#!">

                    <!-- Heading -->
                    <h3>
                      CGG was not in a urge but has to do something.
                    </h3>

                    <!-- Text -->
                    <p class="mb-0 text-muted">
                      This is the body text of the blog post to give visitors an idea of what the post is about beyond just the title. It can be a long snippet, a short snippet, whatever you prefer the size of card and description to be.
                    </p>

                  </a>

                  <!-- Meta -->
                  <a class="card-meta" href="#!">

                    <!-- Divider -->
                    <hr class="card-meta-divider">

                    <!-- Avatar -->
                    <div class="avatar avatar-sm me-2">
                      <%= image_tag("avatars/avatar-fix.jpg", class: "avatar-img rounded-circle") %>
                    </div>

                    <!-- Author -->
                    <h6 class="text-uppercase text-muted me-2 mb-0">
                      François-Xavier Baud
                    </h6>

                    <!-- Date -->
                    <p class="h6 text-uppercase text-muted mb-0 ms-auto">
                      <time datetime="2019-05-29">May 17</time>
                    </p>

                  </a>

                </div>

              </div>
            </div>

            <!-- Card -->
            <div class="card card-row shadow-light-lg bg-cover overlay overlay-dark overlay-80 text-white mb-6" style="background-image: url(<%= asset_path('covers/cover-8.jpg') %>">
              <div class="row gx-0">
                <div class="col-12 col-md-6">
                  <!-- Body -->
                  <a class="card-body" href="#!">
                    <!-- Heading -->
                    <h3>
                      Consolidation as a defensive move
                    </h3>
                    <!-- Text -->
                    <p class="mb-0 text-white-80">
                      Series of deals: Technip & FMC, Halliburton & BakerHugues
                    </p>
                  </a>
                  <!-- Meta -->
                  <a class="card-meta" href="#!">
                    <!-- Divider -->
                    <hr class="card-meta-divider bg-white-20">
                  </a>
                </div>
              </div> <!-- / .row -->
            </div>

            <!-- Card -->
            <div class="card card-row shadow-light-lg bg-cover overlay overlay-gradient-dark-end overlay-20 text-white mb-6" style="background-image: url(<%= asset_path('photos/photo-cgg-hq.jpg') %>">
              <div class="row gx-0 justify-content-end">
                <div class="col-12 col-md-6">

                  <!-- Body -->
                  <a class="card-body" href="#!">

                    <!-- Heading -->
                    <h3>
                      Background Photo + Gradient Overlay.
                    </h3>

                    <!-- Text -->
                    <p class="mb-0 text-white-80">
                      <div>
                    <canvas id="myChartCggPnl"></canvas>
                  </div>
                    </p>

                  </a>

                  <!-- Meta -->
                  <a class="card-meta" href="#!">

                    <!-- Divider -->
                    <hr class="card-meta-divider bg-white-20">

                    <!-- Avatar -->
                    <div class="avatar avatar-sm me-2">
                      <%= image_tag("avatars/avatar-fix.jpg", class: "avatar-img rounded-circle") %>
                    </div>

                    <!-- Author -->
                    <h6 class="text-uppercase text-white-80 me-2 mb-0">
                      François-Xavier Baud
                    </h6>

                    <!-- Date -->
                    <p class="h6 text-uppercase text-white-80 mb-0 ms-auto">
                      <time datetime="2019-05-02">May 02</time>
                    </p>

                  </a>

                </div>
              </div> <!-- / .row -->
            </div>
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </section>

    <section class="pt-7 pt-md-10 bg-light">
      <div class="container">
        <div class="row align-items-center mb-5">
          <div class="col-12 col-md">
              <!-- Heading -->
              <h3 class="mb-0">
                Related Work
              </h3>
              <!-- Text -->
              <p class="mb-0 text-muted">
                Other goodies that are similar to this one.
              </p>
            </div>
            <div class="col-12 col-md-auto">
              <!-- Button -->
              <%= link_to "Back", root_path, class: "btn btn-sm btn-outline-gray-300 d-none d-md-inline" %>
          </div>
        </div>

        <div class="row">
          <div class="col-12 col-md-6 col-lg-4 d-flex">
            <!-- Card -->
            <%= link_to jazztel_path, class: "card mb-6 mb-lg-6 shadow-light-lg", data: { turbolinks: false } do %>
              <!-- Image -->
              <div class="card-zoom mt-2">
                <%= image_tag("photos/logo_jazztel.png", class: "card-img-top") %>
              </div>
              <!-- Body -->
              <div class="card-body">
                <!-- Shape -->
                <div class="shape shape-bottom-100 shape-fluid-x svg-shim text-white">
                </div>
                <!-- Preheading -->
                <h6 class="text-uppercase mb-1 text-muted">Stock story</h6>
                <!-- Heading -->
                <h4 class="mb-0">Jazztel</h4>
              </div>
            <% end %>
          </div>

          <div class="col-12 col-md-6 col-lg-4 d-flex">
            <!-- Card -->
            <%= link_to futuren_path, class: "card mb-6 mb-lg-6 shadow-light-lg", data: { turbolinks: false } do %>
              <!-- Image -->
              <div class="card-zoom mt-2">
                <%= image_tag("photos/logo_futuren.png", class: "card-img-top") %>
              </div>
              <!-- Body -->
              <div class="card-body">
                <!-- Shape -->
                <div class="shape shape-bottom-100 shape-fluid-x svg-shim text-white">
                </div>
                <!-- Preheading -->
                <h6 class="text-uppercase mb-1 text-muted">Stock story</h6>
                <!-- Heading -->
                <h4 class="mb-0">Futuren</h4>
              </div>
            <% end %>
          </div>
        </div>
      </div> <!-- / .container -->
    </section>


    <!-- CTA -->
    <section class="pt-6 pt-md-8 bg-gray-200">
      <div class="container pb-6 pb-md-8 border-bottom border-gray-300">
        <div class="row align-items-center">
          <div class="col-12 col-md">

            <!-- Heading -->
            <h3 class="mb-1 fw-bold">
              Get our stories delivered
            </h3>

            <!-- Text -->
            <p class="fs-lg text-muted mb-6 mb-md-0">
              From us to your inbox weekly.
            </p>

          </div>
          <div class="col-12 col-md-5">

            <!-- Form -->
            <form>
              <div class="row">
                <div class="col">

                  <!-- Input -->
                  <input type="email" class="form-control" placeholder="Enter your email">

                </div>
                <div class="col-auto ms-n5">

                  <!-- Button -->
                  <button class="btn btn-primary" type="submit">
                    Subscribe
                  </button>

                </div>
              </div> <!-- / .row -->
            </form>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </section>

app/views/pages/futuren.html.erb
    <section class="pt-8 pt-md-11">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10 col-lg-9 col-xl-8">
            <!-- Heading -->
            <h1 class="display-3 fw-bold text-center">
              Help a Renewable energy pioneer to transition its capital structure
            </h1>

            <!-- Text -->
            <p class="lead mb-7 text-center text-muted">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec condimentum quam.
              Fusce pellentesque faucibus lorem at viverra. Integer at feugiat odio. In placerat
              euismod risus proin.
            </p>

            <!-- Meta -->
            <div class="row align-items-center py-5 border-top border-bottom">
              <div class="col-auto">
                <!-- Avatar -->
                <div class="avatar avatar-lg">
                  <%= image_tag("avatars/avatar-fix.jpg", class: "avatar-img rounded-circle") %>
                </div>
              </div>
              <div class="col ms-n5">
                <!-- Name -->
                <h6 class="text-uppercase mb-0">
                  François-Xavier Baud
                </h6>

                <!-- Date -->
                <time class="fs-sm text-muted" datetime="2019-05-20">
                  Published on May 20, 2019
                </time>
              </div>
              <div class="col-auto">
                <!-- Share -->
                <span class="h6 text-uppercase text-muted d-none d-md-inline me-4">
                  Share:
                </span>

                <!-- Icons -->
                <ul class="d-inline list-unstyled list-inline list-social">
                  <li class="list-inline-item list-social-item me-3">
                    <a href="#!" class="text-decoration-none">
                      <%= image_tag("icons/social/instagram.svg", class: "list-social-icon") %>
                    </a>
                  </li>
                  <li class="list-inline-item list-social-item me-3">
                    <a href="#!" class="text-decoration-none">
                      <%= image_tag("icons/social/facebook.svg", class: "list-social-icon") %>
                    </a>
                  </li>
                  <li class="list-inline-item list-social-item me-3">
                    <a href="#!" class="text-decoration-none">
                      <%= image_tag("icons/social/twitter.svg", class: "list-social-icon") %>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

    <!-- SECTION -->
    <section class="pt-6 pt-md-8">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10 col-lg-9 col-xl-8">
            <!-- Text -->
            <p>
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi reiciendis odio
              perferendis libero saepe voluptatum fugiat dolore voluptates aut, ut quas doloremque
              quo ad quis ipsum molestias neque pariatur commodi.
            </p>
            <p class="mb-0">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Doloribus, quidem, earum!
              Quo fugiat voluptates similique quidem dolorem ex non quibusdam odio suscipit error,
              maiores, itaque blanditiis vel, sed, cum velit?
            </p>
          </div>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

    <!-- SECTION -->
    <section class="pt-6 pt-md-8">
      <div class="container">
        <div class="row justify-content-center">
            <canvas id="myChart"></canvas>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

    <!-- SECTION -->
    <section class="pt-6 pt-md-8">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10 col-lg-9 col-xl-8">
            <!-- Heading -->
            <h2 class="fw-bold">
              Big heading for a new topic
            </h2>

            <!-- Text -->
            <p class="mb-7">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi reiciendis odio
              perferendis libero saepe voluptatum fugiat dolore voluptates aut, ut quas doloremque
              quo ad quis ipsum molestias neque pariatur commodi.
            </p>

            <!-- Divider -->
            <hr class="hr-md mb-7 mx-auto" />

            <!-- Blockquote -->
            <blockquote class="blockquote mb-7">
              <p class="h2 mb-0 text-center text-primary-desat">
                “So many teams struggle to make their onboarding experience anywhere near as good as
                their core product, so the results of this is poor retention”
              </p>
            </blockquote>

            <!-- Divider -->
            <hr class="hr-md mb-7 mx-auto" />

            <!-- Text -->
            <p class="mb-0">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Excepturi reiciendis odio
              perferendis libero saepe voluptatum fugiat dolore voluptates aut, ut quas doloremque
              quo ad quis ipsum molestias neque pariatur commodi.
            </p>
          </div>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

    <!-- SECTION -->
    <section class="pt-6 pt-md-8">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10">
            <div class="row gx-4">
              <div class="col-6">

                <!-- Image -->
                <div>
                  <canvas id="myChartJazztel"></canvas>
                </div>

                <!-- Image -->
                <div>
                  <canvas id="myChart"></canvas>
                </div>

              </div>
              <div class="col-6">

                <!-- Image -->
                <div>
                  <canvas id="myChart"></canvas>
                </div>

                <!-- Image -->
                <div>
                  <canvas id="myChartJazztelPnl"></canvas>
                </div>

              </div>
            </div>
            <!-- / .row -->
          </div>
        </div>
      </div>
    </section>

    <!-- SECTION -->
    <section class="py-6 py-md-8">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-12 col-md-10 col-lg-9 col-xl-8">
            <!-- Heading -->
            <h3 class="fw-bold">
              Small heading for a smaller transition
            </h3>

            <!-- Text -->
            <p class="mb-7">
              Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aliquam ducimus provident,
              quos sint hic, quidem voluptatibus. Quasi, distinctio cupiditate, omnis vitae maxime
              nisi eum similique libero ad dolore sint tempora.
            </p>

            <!-- List -->
            <ul class="list-unstyled mb-0">
              <li class="d-flex">
                <!-- Check -->
                <div class="badge badge-rounded-circle bg-success-soft mt-1 me-4">
                  <i class="fe fe-check"></i>
                </div>

                <!-- Text -->
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis quo labore,
                  deleniti optio non, voluptate illo doloribus odio iure molestiae eos tempora
                  nobis.
                </p>
              </li>
              <li class="d-flex">
                <!-- Check -->
                <div class="badge badge-rounded-circle bg-success-soft mt-1 me-4">
                  <i class="fe fe-check"></i>
                </div>

                <!-- Text -->
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis quo labore,
                  deleniti optio non, voluptate illo doloribus odio iure molestiae eos tempora
                  nobis.
                </p>
              </li>
              <li class="d-flex">
                <!-- Check -->
                <div class="badge badge-rounded-circle bg-success-soft mt-1 me-4">
                  <i class="fe fe-check"></i>
                </div>

                <!-- Text -->
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Facilis quo labore,
                  deleniti optio non, voluptate illo doloribus odio iure molestiae eos tempora
                  nobis.
                </p>
              </li>
            </ul>
          </div>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

    <!-- SHAPE -->
    <div class="position-relative">
      <div class="shape shape-bottom shape-fluid-x svg-shim text-light">
        {{> curves/curve-1}}
      </div>
    </div>

    <!-- RELATED -->
    <section class="pt-7 pt-md-10 bg-light">
      <div class="container">
        <div class="row align-items-center mb-5">
          <div class="col-12 col-md">

            <!-- Heading -->
            <h3 class="mb-0">
              Related Work
            </h3>

            <!-- Text -->
            <p class="mb-0 text-muted">
              Other goodies that are similar to this one.
            </p>

          </div>
          <div class="col-12 col-md-auto">
            <!-- Button -->
            <%= link_to "Back", root_path, class: "btn btn-sm btn-outline-gray-300 d-none d-md-inline" %>
          </div>
        </div> <!-- / .row -->
        <div class="row">
          <div class="col-12 col-md-6 col-lg-4 d-flex">

            <!-- Card -->
            <%= link_to cgg_path, class: "card mb-6 mb-lg-0 shadow-light-lg", data: { turbolinks: false }  do %>

              <!-- Image -->
              <div class="card-zoom mt-2">
                <%= image_tag("photos/logo_CGG.png", class: "card-img-top") %>
              </div>

              <!-- Body -->
              <div class="card-body">

                <!-- Shape -->
                <div class="shape shape-bottom-100 shape-fluid-x svg-shim text-white">

                </div>

                <!-- Preheading -->
                <h6 class="text-uppercase mb-1 text-muted">Stock story</h6>

                <!-- Heading -->
                <h4 class="mb-0">CGG</h4>

              </div>

            <% end %>

          </div>
          <div class="col-12 col-md-6 col-lg-4 d-flex">

            <!-- Card -->

              <%= link_to solocal_path, class: "card d-md-none d-lg-flex shadow-light-lg", data: { turbolinks: false }  do %>

              <!-- Image -->
              <div class="card-zoom">
                <%= image_tag("photos/logo_pagesjaunes.png", class: "card-img-top") %>
              </div>

              <!-- Body -->
              <div class="card-body">

                <!-- Shape -->
                <div class="shape shape-bottom-100 shape-fluid-x svg-shim text-white">

                </div>

                <!-- Preheading -->
                <h6 class="text-uppercase mb-1 text-muted">Capital structure turn around for a business transformation</h6>

                <!-- Heading -->
                <h4 class="mb-0">From Print to Digital </h4>

              </div>

            <% end %>

          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->
    </section>

    <!-- CTA -->
    <section class="pt-7 pt-md-10 bg-light">
      <div class="container py-6 py-md-8 border-top border-bottom border-gray-300">
        <div class="row align-items-center">
          <div class="col-12 col-md">
            <!-- Heading -->
            <h3 class="mb-1 fw-bold">
              Get our stories delivered
            </h3>

            <!-- Text -->
            <p class="fs-lg text-muted mb-6 mb-md-0">
              From us to your inbox weekly.
            </p>
          </div>
          <div class="col-12 col-md-5">
            <!-- Form -->
            <form>
              <div class="row">
                <div class="col">
                  <!-- Input -->
                  <input type="email" class="form-control" placeholder="Enter your email" />
                </div>
                <div class="col-auto ms-n5">
                  <!-- Button -->
                  <button class="btn btn-primary" type="submit">
                    Subscribe
                  </button>
                </div>
              </div>
              <!-- / .row -->
            </form>
          </div>
        </div>
        <!-- / .row -->
      </div>
      <!-- / .container -->
    </section>

app/views/shared/_footer.html.erb
<footer class="py-8 py-md-11 @@classList">
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-4 col-lg-3">
        <!-- Text -->
        <p class="text-gray-700 mb-2">
          Restructure to thrive.
        </p>
      </div>
    </div>
  </div> <!-- / .container -->
</footer>

app/views/shared/_gtm_body.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-M9FQQ4H"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

<!-- Global site tag (gtag.js) - Google Ads: 973796360 -->
<script async src="https://www.googletagmanager.com/gtag/js?id=AW-973796360"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'AW-973796360');
</script>

app/views/shared/_gtm_head.html.erb
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-M9FQQ4H');</script>
<!-- End Google Tag Manager -->

<!-- Event snippet for Website traffic conversion page -->
<script>
  gtag('event', 'conversion', {'send_to': 'AW-973796360/1ilhCMD445cCEIjoq9AD'});
</script>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg @@classList">
  <div class="container">

    <!-- Brand -->
    <a class="navbar-brand" href="/">
      <% image_tag("logo_boussard_gavaudan_white.png", class: "navbar-brand-img") %>
    </a>

    <!-- Toggler -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <!-- Collapse -->
    <div class="collapse navbar-collapse" id="navbarCollapse">

      <!-- Toggler -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fe fe-x"></i>
      </button>

  </div>
</nav>